[package]
name = "TicTacToe"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
iroh = "0.30.0"
tokio = { version = "1.42.0", features = ["full"] }
rand = "0.8.5"

